Add notebook for data fusion showcase
openEOPlatform/SH_backend_notebooks pull request #1
Opened 2023-11-17 09:10 UTC by zansinergise

2023-11-17 13:11 UTC, zcernigoj commented
This is for a separate MR, just mentioning here for convenience

`notebooks/.ipynb_checkpoints/5_SH_backend_data_fusion_mean_NDVI-checkpoint.ipynb` and other "checkpoints" files in `notebooks/.ipynb_checkpoints` folder are not needed and can be removed.

Also, to avoid committing new "checkpoints" files, these 2 lines should be added to `.gitignore`:

```
.ipynb_checkpoints
*/.ipynb_checkpoints/*
```

2023-11-17 13:18 UTC, zcernigoj commented
Please add this notebook to the list in readme

2023-11-17 13:29 UTC, zcernigoj commented on notebooks/5_SH_backend_data_fusion_mean_NDVI.ipynb
> +    "connection = openeo.connect(\"http://127.0.0.1:5000\")\n",
The URL will need to change when the data fusion will be deployed

2023-11-17 13:47 UTC, zcernigoj requested changes
Only the URL and adding the notebook to the list in the readme. Other than that it looks ok and works when tested with locally deployed backend :+1:

2023-11-17 14:34 UTC, zansinergise commented
Updated the readme with a short description and changed the localhost url back to the production one, so the notebook will work normally when we merge the data fusion

2023-11-22 13:18 UTC, zcernigoj approved these changes

2023-11-22 13:37 UTC, merged